"""What the bot decides, tested without a network.

The bot's risky surface is not its HTTP calls, it is its judgements: whether a
mention is a request or a takedown, what a screen reader is told, and — the one
that matters most — which exit codes end a request versus leave it to be tried
again. A code that fell through the wrong branch would either strand a person
with no answer or answer them repeatedly.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "render"))

import bot
import exits


class _Source:
    handle = "someone.bsky.social"
    text = "a post worth rendering"


# --- alt text ---------------------------------------------------------------


def test_alt_text_names_the_tool_the_author_and_the_words():
    alt = bot.alt_text(_Source())
    assert alt.startswith("Generated by skeetio\nUser: someone.bsky.social\nContent: ")
    assert _Source.text in alt


def test_alt_text_says_what_it_is_before_quoting_anyone():
    """A listener must not hear someone else's words in the first person with no
    idea whose they are or where they came from."""
    alt = bot.alt_text(_Source())
    assert alt.index("skeetio") < alt.index(_Source.handle) < alt.index(_Source.text)


def test_alt_text_is_bounded_and_keeps_the_attribution():
    """Truncation must eat the quote, never the credit — the opposite order
    would produce an alt that quotes someone anonymously."""
    class Long:
        handle = "someone.bsky.social"
        text = "x" * 5000

    alt = bot.alt_text(Long(), limit=200)
    assert len(alt) <= 200
    assert "Generated by skeetio" in alt and Long.handle in alt
    assert alt.rstrip().endswith("…")


def test_alt_text_is_never_empty():
    """It shipped defaulting to empty on a video whose entire content is text."""
    class Blank:
        handle = "someone.bsky.social"
        text = ""

    assert bot.alt_text(Blank()).strip()


# --- request vs takedown ----------------------------------------------------


@pytest.mark.parametrize("text", [
    "@skeetio remove",
    "@skeetio please delete this",
    "hey @skeetio take it down",
    "@skeetio REMOVE",
])
def test_a_takedown_is_recognised(text):
    assert bot.wants_removal(text, "skeetio")


@pytest.mark.parametrize("text", [
    "@skeetio",
    "@skeetio do this one",
    "@skeetio this is great",
])
def test_an_ordinary_request_is_not_a_takedown(text):
    assert not bot.wants_removal(text, "skeetio")


def test_the_bots_own_handle_cannot_trigger_a_takedown():
    """A bot called @remove.example would otherwise read every mention of itself
    as a request to delete something."""
    assert not bot.wants_removal("@remove.example do this one", "remove.example")


# --- the exit-code policy ---------------------------------------------------
# The property under test: every documented code lands in exactly one of
# "answer and close", "leave for retry", or "stop the bot" — and none falls
# through to a fourth, undefined behaviour.


PERMANENT = {exits.NO_TEXT, exits.UNRENDERABLE_SCRIPT}
HALT = {exits.BAD_ENV, exits.IDENTITY_MISMATCH}


def test_every_documented_code_has_a_defined_disposition():
    for e in exits.CONTRACT:
        if e.code == exits.OK:
            continue
        assert (
            e.code in PERMANENT
            or exits.is_retryable(e.code)
            or e.code in HALT
            or e.code == exits.EMPTY_POST_TEXT
        ), f"{e.name} ({e.code}) has no disposition — the bot would not know what to do"


def test_permanent_codes_are_answered_rather_than_retried():
    """Someone whose post cannot be rendered gets told once. Retrying a
    permanent failure means never telling them and never stopping."""
    for code in PERMANENT:
        assert not exits.is_retryable(code)


def test_operator_errors_never_look_retryable_to_the_bot():
    """Retrying past IDENTITY_MISMATCH is retrying past the guard that stops the
    bot posting as the wrong account."""
    for code in HALT:
        assert not exits.is_retryable(code)


def test_undocumented_codes_are_the_case_the_bot_must_handle():
    """The real hazard: a crash exits 1, argparse exits 2, a signal gives a
    negative return. None are in the contract, and `code // 10` puts them in no
    group — so the bot cannot dispatch on the tens digit alone and must check
    membership."""
    for code in (1, 2, 3, -9, 99):
        assert code not in exits.BY_CODE
        assert not exits.is_retryable(code) or code // 10 in (2, 4)


def test_fetch_failed_is_retryable_and_transport_shaped():
    """It exists because a network error used to escape as exit 1, which is in
    no group at all."""
    assert exits.FETCH_FAILED in exits.BY_CODE
    assert exits.is_retryable(exits.FETCH_FAILED)


# --- reply keys -------------------------------------------------------------


def test_a_note_and_a_video_never_share_a_record_key():
    """Both are answers to the same request. Sharing a key would mean the second
    collides with the first and disappears without an error."""
    import ledger

    req = "at://did:plc:x/app.bsky.feed.post/abc"
    assert ledger.rkey_for(req) != ledger.rkey_for(req + "#note")


# --- what handle() actually does, with the network taken away ---------------
# The branch logic is where the consent properties live: who gets answered, who
# gets refused, and what is written down about it. Driven through handle() end
# to end rather than asserted about its parts.

import ledger  # noqa: E402
from post import Post  # noqa: E402

BOT = "did:plc:bot"
ASKER = "did:plc:asker"
AUTHOR = "did:plc:author"


def _post(uri, did, text="", parent=None, handle="x.bsky.social") -> Post:
    root = {"uri": parent, "cid": "bafyroot"} if parent else None
    return Post(uri=uri, cid="bafy" + uri[-4:], text=text, handle=handle,
                display_name="X", did=did, avatar_url=None, created_at="2026-08-19T00:00:00Z",
                likes=0, reposts=0, replies=0, quotes=0,
                reply_parent_uri=parent, reply_root=root)


class _Opts:
    bot_did = BOT
    bot_handle = "skeetio.bsky.social"
    dry_run = True
    env = "/nonexistent"
    expect_account = None
    dur = 10.0
    generic = False
    limit = 25


@pytest.fixture(autouse=True)
def _isolated(tmp_path, monkeypatch):
    monkeypatch.setattr(ledger, "STATE", tmp_path)
    monkeypatch.setattr(ledger, "LEDGER", tmp_path / "ledger.jsonl")
    # Any real HTTP is a bug in the test, not a slow test.
    monkeypatch.setattr(bot, "_req", lambda *a, **k: pytest.fail("bot made a network call"))


REQ_URI = "at://did:plc:asker/app.bsky.feed.post/req"
SRC_URI = "at://did:plc:author/app.bsky.feed.post/src"


def _note(uri=REQ_URI, did=ASKER):
    return {"uri": uri, "author": {"did": did}}


def test_a_mention_that_is_not_a_reply_is_refused_and_recorded(monkeypatch):
    """There is no post above it to render. The person still gets told, once."""
    monkeypatch.setattr(bot.P, "fetch", lambda u: _post(REQ_URI, ASKER, "@skeetio do it"))
    said = []
    monkeypatch.setattr(bot, "say", lambda req, text, o, t: said.append(text))

    bot.handle(_note(), _Opts(), "token")

    rows = ledger.rows()
    assert [r["outcome"] for r in rows] == ["refused"]
    assert rows[0]["note"] == "not a reply"
    assert said, "the requester was left with no answer at all"


def test_the_bot_never_answers_itself(monkeypatch):
    """Its own posts come back as notifications. Answering them is a loop."""
    monkeypatch.setattr(bot.P, "fetch", lambda u: pytest.fail("should not have fetched"))
    bot.handle(_note(did=BOT), _Opts(), "token")
    assert ledger.rows() == []


def test_an_already_answered_request_is_left_alone(monkeypatch):
    ledger.append(ledger.Row(outcome="posted", request_uri=REQ_URI, requester_did=ASKER,
                             source_uri=SRC_URI, source_did=AUTHOR, at=ledger.now(),
                             reply_uri="at://bot/x"))
    monkeypatch.setattr(bot.P, "fetch", lambda u: pytest.fail("re-read an answered request"))
    bot.handle(_note(), _Opts(), "token")
    assert len(ledger.rows()) == 1, "a second row means it would have posted twice"


def test_a_request_claims_before_it_renders(monkeypatch):
    """The claim has to be on disk *before* the post goes out, or a crash in
    between leaves nothing saying the attempt ever happened."""
    order = []
    monkeypatch.setattr(bot.P, "fetch", lambda u: (
        _post(REQ_URI, ASKER, "@skeetio do it", parent=SRC_URI)
        if u == REQ_URI else _post(SRC_URI, AUTHOR, "words worth rendering")))
    monkeypatch.setattr(bot, "render_and_reply",
                        lambda *a: (order.append(ledger.rows()[-1]["outcome"]), (exits.OK, {}))[1])

    bot.handle(_note(), _Opts(), "token")

    assert order == ["claimed"], "rendering started with no claim written"
    assert [r["outcome"] for r in ledger.rows()] == ["claimed", "posted"]


def test_a_retryable_failure_writes_no_terminal_row(monkeypatch):
    """So the stale claim releases it and the next pass tries again. A terminal
    row here would strand the requester permanently on a transient error."""
    monkeypatch.setattr(bot.P, "fetch", lambda u: (
        _post(REQ_URI, ASKER, "@skeetio do it", parent=SRC_URI)
        if u == REQ_URI else _post(SRC_URI, AUTHOR, "words")))
    monkeypatch.setattr(bot, "render_and_reply", lambda *a: (exits.FETCH_FAILED, {}))

    bot.handle(_note(), _Opts(), "token")

    assert [r["outcome"] for r in ledger.rows()] == ["claimed"]
    assert not ledger.handled(REQ_URI, now=ledger.now() + ledger.STALE_CLAIM_SECS + 1)


def test_a_permanent_failure_answers_and_closes(monkeypatch):
    monkeypatch.setattr(bot.P, "fetch", lambda u: (
        _post(REQ_URI, ASKER, "@skeetio do it", parent=SRC_URI)
        if u == REQ_URI else _post(SRC_URI, AUTHOR, "")))
    monkeypatch.setattr(bot, "render_and_reply", lambda *a: (exits.NO_TEXT, {}))
    said = []
    monkeypatch.setattr(bot, "say", lambda req, text, o, t: said.append(text))

    bot.handle(_note(), _Opts(), "token")

    assert [r["outcome"] for r in ledger.rows()] == ["claimed", "refused"]
    assert ledger.handled(REQ_URI, now=9e9)
    assert said and "no text" in said[0].lower()


def test_an_unauthorised_takedown_deletes_nothing(monkeypatch):
    """The mechanism takes orders from a mention, so this is the branch that
    stops any passer-by removing someone else's video.

    It must still *record* the refusal. Writing nothing looks tidier and means
    the request is re-read on every pass, forever."""
    ledger.append(ledger.Row(outcome="posted", request_uri=REQ_URI, requester_did=ASKER,
                             source_uri=SRC_URI, source_did=AUTHOR, at=ledger.now(),
                             reply_uri="at://bot/vid"))
    monkeypatch.setattr(bot.P, "fetch", lambda u: _post(
        "at://did:plc:nobody/app.bsky.feed.post/r2", "did:plc:nobody",
        "@skeetio remove", parent="at://bot/vid"))
    calls = []
    monkeypatch.setattr(bot, "_req", lambda url, **kw: calls.append(url) or {})

    class Live(_Opts):
        dry_run = False

    note = _note(uri="at://did:plc:nobody/app.bsky.feed.post/r2", did="did:plc:nobody")
    bot.handle(note, Live(), "token")

    assert not calls, "a stranger's remove request reached the network"
    assert "removed" not in [r["outcome"] for r in ledger.rows()]
    assert ledger.handled(note["uri"], now=9e9), (
        "the refusal was not recorded, so it will be re-read on every pass forever"
    )


@pytest.mark.parametrize("actor", [AUTHOR, ASKER])
def test_the_author_and_the_requester_can_each_take_it_down(monkeypatch, actor):
    """Run live against a captured transport, not in --dry-run. The earlier
    version of this test ran dry and asserted that a `removed` row appeared —
    which is to say it asserted the dry-run ledger leak as the specification."""
    ledger.append(ledger.Row(outcome="posted", request_uri=REQ_URI, requester_did=ASKER,
                             source_uri=SRC_URI, source_did=AUTHOR, at=ledger.now(),
                             reply_uri="at://did:plc:bot/app.bsky.feed.post/vid"))
    monkeypatch.setattr(bot.P, "fetch", lambda u: _post(
        "at://x/app.bsky.feed.post/r2", actor, "@skeetio remove",
        parent="at://did:plc:bot/app.bsky.feed.post/vid"))
    calls = []
    monkeypatch.setattr(bot, "_req", lambda url, **kw: calls.append(url) or {})

    class Live(_Opts):
        dry_run = False

    bot.handle(_note(uri="at://x/app.bsky.feed.post/r2", did=actor), Live(), "token")

    assert calls and calls[0].endswith("deleteRecord"), "nothing was deleted"
    assert ledger.rows()[-1]["outcome"] == "removed"
    assert ledger.live_for_source(AUTHOR) == []


def test_a_dry_run_neither_deletes_nor_records(monkeypatch):
    """A dry run that appends a terminal row consumes the request permanently and
    can record a takedown that never happened — after which retract.py reports
    nothing to remove for a video that is still up. The whole point of --dry-run
    is that the world is unchanged afterwards."""
    ledger.append(ledger.Row(outcome="posted", request_uri=REQ_URI, requester_did=ASKER,
                             source_uri=SRC_URI, source_did=AUTHOR, at=ledger.now(),
                             reply_uri="at://bot/vid"))
    before = len(ledger.rows())
    monkeypatch.setattr(bot.P, "fetch", lambda u: _post(
        "at://x/app.bsky.feed.post/r2", AUTHOR, "@skeetio remove", parent="at://bot/vid"))

    note = _note(uri="at://x/app.bsky.feed.post/r2", did=AUTHOR)
    bot.handle(note, _Opts(), "token")          # _Opts.dry_run is True

    assert len(ledger.rows()) == before, "a dry run wrote to the ledger"
    assert not ledger.handled(note["uri"], now=9e9), (
        "a dry run consumed the request, so the real pass will never serve it"
    )


def test_a_render_request_mentioning_deletion_still_renders(monkeypatch):
    """The removal branch used to trigger on the wording alone. Any ordinary
    request containing 'remove' or 'delete' took that path, matched no ledger
    row, returned having written nothing, and was re-read every three minutes
    forever. Detection signal that it had not yet fired in production: the cron
    log still read `0 unanswered`."""
    monkeypatch.setattr(bot.P, "fetch", lambda u: (
        _post(REQ_URI, ASKER, "@skeetio delete this from my memory please", parent=SRC_URI)
        if u == REQ_URI else _post(SRC_URI, AUTHOR, "words worth rendering")))
    rendered = []
    monkeypatch.setattr(bot, "render_and_reply",
                        lambda *a: (rendered.append(1), (exits.OK, {}))[1])

    bot.handle(_note(), _Opts(), "token")

    assert rendered, "a render request was swallowed by the removal branch"
    assert [r["outcome"] for r in ledger.rows()] == ["claimed", "posted"]


def test_an_authorised_takedown_actually_calls_deleteRecord(monkeypatch):
    """The test above runs in --dry-run, so it proves who is *allowed* to delete
    and not that anything is deleted. This one runs for real against a captured
    transport: without it, a takedown path that only ever wrote a ledger row
    saying "removed" would pass the whole suite while leaving the video up."""
    ledger.append(ledger.Row(outcome="posted", request_uri=REQ_URI, requester_did=ASKER,
                             source_uri=SRC_URI, source_did=AUTHOR, at=ledger.now(),
                             reply_uri="at://did:plc:bot/app.bsky.feed.post/vidkey"))
    monkeypatch.setattr(bot.P, "fetch", lambda u: _post(
        "at://x/app.bsky.feed.post/r2", AUTHOR, "@skeetio remove",
        parent="at://did:plc:bot/app.bsky.feed.post/vidkey"))

    calls = []
    monkeypatch.setattr(bot, "_req", lambda url, **kw: calls.append((url, kw)) or {})

    class Live(_Opts):
        dry_run = False

    bot.handle(_note(uri="at://x/app.bsky.feed.post/r2", did=AUTHOR), Live(), "token")

    assert calls, "nothing was sent — the video would still be up"
    url, kw = calls[0]
    assert url.endswith("com.atproto.repo.deleteRecord")
    body = json.loads(kw["body"])
    assert body["repo"] == BOT and body["rkey"] == "vidkey", (
        f"deleted the wrong record: {body}"
    )
    assert ledger.rows()[-1]["outcome"] == "removed"


# --- the disposition bug, which shipped and stranded a real request ---------
# The first version wrote a terminal "refused" row for ANY code that was not
# retryable and not a known-permanent one. An archive.org timeout escaped
# make_video as a bare exit 1, landed in that branch, and permanently closed a
# request that would have succeeded on the next try. The test that was supposed
# to cover this only asserted things about the `exits` module, so it passed.
# These drive handle() instead.


def _wire(monkeypatch, code):
    monkeypatch.setattr(bot.P, "fetch", lambda u: (
        _post(REQ_URI, ASKER, "@skeetio do it", parent=SRC_URI)
        if u == REQ_URI else _post(SRC_URI, AUTHOR, "words")))
    monkeypatch.setattr(bot, "render_and_reply", lambda *a: (code, {}))
    monkeypatch.setattr(bot, "say", lambda *a, **k: None)


@pytest.mark.parametrize("code", [1, 2, -9, 137])
def test_an_undocumented_exit_does_not_permanently_close_a_request(monkeypatch, code):
    """The actual regression. An error we cannot classify must not be grounds
    for refusing someone forever."""
    _wire(monkeypatch, code)
    bot.handle(_note(), _Opts(), "token")

    outcomes = [r["outcome"] for r in ledger.rows()]
    assert "refused" not in outcomes and "failed" not in outcomes, (
        f"exit {code} wrote {outcomes} — an unclassifiable error closed the request"
    )
    assert not ledger.handled(REQ_URI, now=ledger.now() + ledger.STALE_CLAIM_SECS + 1), (
        "the request will never be retried"
    )


def test_a_clip_fetch_failure_is_retried_not_refused(monkeypatch):
    """archive.org being slow is the single most likely failure in the whole
    pipeline — the clip is up to 180 MB."""
    _wire(monkeypatch, exits.CLIP_FETCH_FAILED)
    bot.handle(_note(), _Opts(), "token")
    assert [r["outcome"] for r in ledger.rows()] == ["claimed"]


def test_retrying_is_bounded(monkeypatch):
    """A released stale claim retries; without a cap, a permanently unreachable
    clip would be retried every half hour forever. Pairing is deterministic, so
    it fails identically each time."""
    _wire(monkeypatch, exits.CLIP_FETCH_FAILED)
    for _ in range(bot.MAX_ATTEMPTS + 1):
        # Each pass sees a released claim, so it tries again.
        bot.handle(_note(), _Opts(), "token")
        for r in list(ledger.rows()):
            pass
        monkeypatch.setattr(ledger, "handled", lambda *a, **k: False)

    outcomes = [r["outcome"] for r in ledger.rows()]
    assert outcomes.count("claimed") <= bot.MAX_ATTEMPTS + 1
    assert outcomes[-1] == "failed", (
        f"never gave up: {outcomes} — this request retries forever"
    )


@pytest.mark.parametrize("code", [exits.BAD_ENV, exits.IDENTITY_MISMATCH])
def test_an_operator_error_stops_the_bot_rather_than_the_request(monkeypatch, code):
    """These are wrong for every request, not for this one. Closing the request
    would blame the person who asked; continuing would keep trying to post as
    the wrong account, which is the guard IDENTITY_MISMATCH exists to be."""
    _wire(monkeypatch, code)
    with pytest.raises(SystemExit) as e:
        bot.handle(_note(), _Opts(), "token")
    assert e.value.code == code
    outcomes = [r["outcome"] for r in ledger.rows()]
    assert "refused" not in outcomes and "failed" not in outcomes, (
        f"an operator error was recorded against the request: {outcomes}"
    )


# --- the boundary itself, which every other test in this file stubs ---------
# C1 survived a 128-test suite because `_req` is monkeypatched in every one of
# them. The suite exercised the logic *between* the boundaries and never the
# boundaries themselves, so an `except` clause naming an exception that can no
# longer arrive looked exactly like a working guard.


def test_every_api_guard_catches_what_req_actually_raises():
    """_req converts urllib's HTTPError into publish.ApiError, which is a
    RuntimeError — disjoint from HTTPError and from OSError. Any handler here
    listening for the old type is unreachable code that reads as a guard.

    Checked against the source rather than by triggering each path: reaching all
    of them for real needs a live server returning specific statuses, which is
    how they went unexercised in the first place.
    """
    import ast
    import urllib.error

    from publish import ApiError

    assert not issubclass(ApiError, urllib.error.HTTPError)
    assert not issubclass(ApiError, OSError), (
        "ApiError became an OSError subclass — the guards below are now "
        "accidentally correct, and this test no longer proves anything"
    )

    offenders = []
    for mod in ("bot.py", "retract.py"):
        src = (Path(__file__).resolve().parent.parent / "render" / mod).read_text()
        for node in ast.walk(ast.parse(src)):
            if not isinstance(node, ast.ExceptHandler) or node.type is None:
                continue
            names = [n.attr if isinstance(n, ast.Attribute) else getattr(n, "id", "")
                     for n in ast.walk(node.type) if isinstance(n, (ast.Name, ast.Attribute))]
            # A handler that expects a failed API call must name ApiError.
            if "HTTPError" in names and "ApiError" not in names:
                offenders.append(f"{mod}:{node.lineno} catches HTTPError without ApiError")
    assert not offenders, (
        "these guards cannot fire — _req raises ApiError, not HTTPError: " + "; ".join(offenders)
    )


def test_an_api_failure_is_caught_rather_than_killing_the_pass(monkeypatch):
    """The operational consequence of C1: an expired app password made every
    poll die with an uncaught RuntimeError, exiting 1. bot-cron.sh only alerts
    on a 3x exit, so the bot stopped answering anyone and said nothing."""
    from publish import ApiError

    def boom(*a, **k):
        raise ApiError("POST", "/xrpc/com.atproto.repo.createRecord", 401, "ExpiredToken")

    monkeypatch.setattr(bot.P, "fetch", lambda u: _post(REQ_URI, ASKER, "@skeetio do it"))
    monkeypatch.setattr(bot, "_req", boom)
    monkeypatch.setattr(bot, "get", lambda *a, **k: {"notifications": [_note()]})

    class Live(_Opts):
        dry_run = False

    # poll() must survive it; the request stays unrecorded so the next pass retries.
    bot.poll(Live(), "token")
    assert not ledger.handled(REQ_URI, now=9e9), (
        "a transient API failure permanently consumed the request"
    )
