"""Two things that were silently wrong until the bot ran unattended.

A present-but-silent audio track shipped a soundless video to a stranger:
`has_audio` only asks whether a stream exists, and the clip had a perfectly good
AAC stream carrying nothing. And the footage cache had no ceiling at all.

Both are tested against real media generated by ffmpeg rather than mocks — the
bug was in what the file actually contained, so a fake file would reproduce the
assumption instead of the condition.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "render"))

import broll

HAVE_FFMPEG = subprocess.run(["ffmpeg", "-version"], capture_output=True).returncode == 0
pytestmark = pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg not on PATH")


def _media(path: Path, *, tone: bool, secs: float = 3.0) -> Path:
    """A tiny mp4 with a real audio stream — either a tone or true silence."""
    audio = (f"sine=frequency=440:duration={secs}" if tone
             else f"anullsrc=r=44100:cl=stereo:d={secs}")
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y",
         "-f", "lavfi", "-i", f"color=c=black:s=64x64:d={secs}",
         "-f", "lavfi", "-i", audio,
         "-shortest", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", str(path)],
        check=True, capture_output=True,
    )
    return path


def test_a_silent_track_still_counts_as_having_audio(tmp_path):
    """The guard that was in place, doing exactly what it says — which is why it
    did not catch this. Pinned so nobody 'fixes' the wrong function."""
    assert broll.has_audio(_media(tmp_path / "silent.mp4", tone=False))


def test_a_silent_source_yields_no_bed_and_says_why(tmp_path):
    """The actual regression: a dead track must not become a dead soundtrack on
    someone's video."""
    src = _media(tmp_path / "silent.mp4", tone=False)
    bed, why = broll.audio_segment(src, tmp_path / "out.m4a", start=0.0, dur=2.0)
    assert bed is None, "a silent source produced an audio bed"
    assert "silent" in why.lower(), f"the reason given was {why!r}"


def test_a_real_soundtrack_is_kept(tmp_path):
    """Guards the guard. A threshold that rejected everything would pass the test
    above while removing sound from every video."""
    src = _media(tmp_path / "tone.mp4", tone=True)
    bed, why = broll.audio_segment(src, tmp_path / "out.m4a", start=0.0, dur=2.0)
    assert bed is not None, f"a clip with real audio was dropped: {why}"


def test_the_threshold_separates_the_two_by_a_wide_margin(tmp_path):
    """If these were close, the cutoff would be a coin-flip on quiet passages."""
    loud = broll.peak_dbfs(_media(tmp_path / "tone.mp4", tone=True))
    quiet = broll.peak_dbfs(_media(tmp_path / "silent.mp4", tone=False))
    assert loud > broll.SILENT_DBFS + 15, f"a real soundtrack measured {loud} dBFS"
    assert quiet < broll.SILENT_DBFS - 5, f"silence measured {quiet} dBFS"


def test_an_unmeasurable_file_is_treated_as_usable(tmp_path):
    """None means 'do not know'. Refusing on a failed measurement would drop
    every clip the day ffmpeg changed its output format — a worse failure than
    the one being prevented."""
    junk = tmp_path / "junk.mp4"
    junk.write_bytes(b"not a video")
    assert broll.peak_dbfs(junk) is None


# --- the cache ceiling ------------------------------------------------------


def _clip(cache: Path, name: str, size: int, atime: float) -> Path:
    p = cache / f"{name}.mp4"
    p.write_bytes(b"\0" * size)
    os.utime(p, (atime, atime))
    return p


def test_eviction_does_nothing_while_under_the_cap(tmp_path):
    """The cap is a bound, not a policy. The whole library is ~2 GB, so in normal
    use this must never remove anything — evicting aggressively would make every
    render re-download from an archive.org that already refuses items for hours."""
    for i in range(5):
        _clip(tmp_path, f"c{i}", 1000, 1000 + i)
    assert broll.evict(tmp_path, cap=1_000_000) == []
    assert len(list(tmp_path.glob("*.mp4"))) == 5


def test_eviction_drops_least_recently_used_first(tmp_path):
    """By access time, not age: a clip that keeps being drawn should survive
    however old it is."""
    old_but_hot = _clip(tmp_path, "hot", 400, atime=9_000_000)
    cold = _clip(tmp_path, "cold", 400, atime=1_000)
    middling = _clip(tmp_path, "mid", 400, atime=5_000)

    dropped = broll.evict(tmp_path, cap=900)

    assert cold in dropped, "the least recently used clip survived"
    assert old_but_hot.exists(), "the most recently used clip was evicted"
    assert sum(p.stat().st_size for p in tmp_path.glob("*.mp4")) <= 900
    assert middling.exists() or middling in dropped


def test_eviction_gets_under_the_cap_even_when_that_means_most_of_it(tmp_path):
    for i in range(6):
        _clip(tmp_path, f"c{i}", 500, atime=1000 + i)
    broll.evict(tmp_path, cap=1000)
    assert sum(p.stat().st_size for p in tmp_path.glob("*.mp4")) <= 1000


def test_eviction_survives_an_empty_cache(tmp_path):
    assert broll.evict(tmp_path, cap=10) == []


# --- clip selection, which reached production untestable --------------------
# Both of its failure modes shipped while 128 tests passed, because the loop
# lived inside an argparse-to-exit-code main() that no test could call.

import make_video  # noqa: E402


class _Pick:
    def __init__(self, ident, start=60.0):
        self.identifier, self.start, self.collection = ident, start, "prelinger"


class _Clip:
    def __init__(self, ident):
        self.identifier, self.path = ident, Path(f"/nonexistent/{ident}.mp4")


def _wire(monkeypatch, *, unfetchable=(), peaks=None):
    peaks = peaks or {}

    def fetch(ident, collection="prelinger"):
        if ident in unfetchable:
            raise TimeoutError("archive.org said no")
        return _Clip(ident)

    monkeypatch.setattr(make_video.broll, "fetch", fetch)
    monkeypatch.setattr(make_video.broll, "peak_dbfs",
                        lambda p, **kw: peaks.get(Path(p).stem, -6.0))


def test_a_silent_clip_is_skipped_rather_than_rendered(monkeypatch):
    """The bug that put a soundless video in front of a stranger. The first
    version detected the silence, printed the reason, and encoded it anyway —
    the check changed the log line and nothing else."""
    _wire(monkeypatch, peaks={"dead": -48.0})
    got = make_video.select_clip([_Pick("dead"), _Pick("good")],
                                 override_start=None, dur=8.0, want_audio=True)
    assert got is not None and got[0].identifier == "good"


def test_an_unfetchable_clip_is_skipped(monkeypatch):
    """archive.org fails per item and for hours; pairing is deterministic, so
    without this the affected post is wedged rather than delayed."""
    _wire(monkeypatch, unfetchable={"gone"})
    got = make_video.select_clip([_Pick("gone"), _Pick("good")],
                                 override_start=None, dur=8.0, want_audio=True)
    assert got is not None and got[0].identifier == "good"
    assert got[2].startswith("drawn, fallback")


def test_the_first_usable_clip_wins_and_is_not_labelled_a_fallback(monkeypatch):
    _wire(monkeypatch)
    got = make_video.select_clip([_Pick("good"), _Pick("other")],
                                 override_start=None, dur=8.0, want_audio=True)
    assert got[0].identifier == "good" and got[2] == "drawn"


def test_silence_is_ignored_when_the_caller_asked_for_no_audio(monkeypatch):
    """--silent means the bed was never wanted, so a quiet clip is not a defect."""
    _wire(monkeypatch, peaks={"dead": -48.0})
    got = make_video.select_clip([_Pick("dead")],
                                 override_start=None, dur=8.0, want_audio=False)
    assert got is not None and got[0].identifier == "dead"


def test_selection_gives_up_rather_than_returning_something_unusable(monkeypatch):
    """Returning a silent or missing clip would be worse than failing: the exit
    code is the bot's whole failure channel, and CLIP_FETCH_FAILED is retryable."""
    _wire(monkeypatch, peaks={"a": -50.0, "b": -49.0}, unfetchable={"c"})
    assert make_video.select_clip([_Pick("a"), _Pick("b"), _Pick("c")],
                                  override_start=None, dur=8.0, want_audio=True) is None


def test_selection_is_bounded(monkeypatch):
    """Past a few tries the far end is not having an item-level problem, and a
    fourth 180 MB request will not help."""
    tried = []
    monkeypatch.setattr(make_video.broll, "fetch",
                        lambda i, collection="prelinger": tried.append(i) or (_ for _ in ()).throw(TimeoutError()))
    make_video.select_clip([_Pick(f"c{i}") for i in range(40)],
                           override_start=None, dur=8.0, want_audio=True)
    assert len(tried) == make_video.CLIP_TRIES
