# pattern: Imperative Shell
"""Answer people who ask for a render, and nobody who did not.

The mechanic, which is the established one — miq.moe has run it since 2023:

    A       someone's post
    └ R     a reply naming this bot
      └ …   the bot's answer, hanging under R

So the bot only ever acts on a request. It never initiates, never approaches an
author, and never posts anything except as a reply to the person who addressed
it. Consent is inherent in the asking; where a stranger asks about someone
else's post, the answer still goes under *their* request rather than being
delivered into the author's mentions.

It also answers `remove`: a reply to one of its own videos, from the author it
was rendered from or from whoever asked for it, takes that video down. That
branch is checked before anything else, because it is the one that has to work
when the rest is broken.

It shells out to make_video and publish rather than importing them. Neither has
a library entry point — both are argparse-to-exit-code — and exits.py was built
for exactly this caller: the tens digit says whether to retry and with what.
Importing them is a real refactor, not a shortcut.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import exits  # noqa: E402
import ledger  # noqa: E402
import post as P  # noqa: E402
from publish import PDS, ApiError, _req, login, read_env  # noqa: E402

RENDER = Path(__file__).resolve().parent

# A request is a mention. Anything else in the notification feed — likes,
# follows, reposts — is not someone asking for something.
WANTED = "mention"

REMOVE_WORDS = ("remove", "delete", "take it down", "takedown")

# How many times a request is picked up before it is written off. Bounds the
# retry that a released stale claim would otherwise repeat forever.
MAX_ATTEMPTS = 3


def get(endpoint: str, token: str, **params) -> dict:
    """Authenticated read against the PDS. post.py talks to the public appview
    and carries no session, which is fine for reading posts and no use for
    reading a notification feed."""
    url = f"{PDS}/xrpc/{endpoint}"
    if params:
        # doseq, because `reasons` is a list parameter and the default encoding
        # would send the repr of a Python list.
        url += "?" + urllib.parse.urlencode(params, doseq=True)
    return _req(url, token=token)


# --- deciding what a notification is ----------------------------------------


def wants_removal(text: str, bot_handle: str) -> bool:
    """Whether a mention is asking for a takedown rather than a render.

    Deliberately blunt: the word has to appear, and the reply has to be to one of
    the bot's own posts (checked by the caller). Being generous here is the safe
    direction — the cost of reading "please delete this" as a render request is
    that someone asking to be left alone gets another video instead.
    """
    body = text.lower().replace(f"@{bot_handle.lower()}", " ")
    return any(w in body for w in REMOVE_WORDS)


def alt_text(source, limit: int = 950) -> str:
    """What a screen reader says. The video's entire content is someone's words,
    so an empty alt — which is what this shipped with — makes it unreadable to
    the people most reliant on the text being text.

    Ordered tool, then author, then content, following the convention miq.moe
    established: a listener hears what the thing *is* before hearing someone
    else's words in the first person.
    """
    head = f"Generated by skeetio\nUser: {source.handle}\nContent: "
    body = source.text.strip()
    room = max(0, limit - len(head))
    if len(body) > room:
        body = body[: max(0, room - 1)].rstrip() + "…"
    return head + body


# --- the two things the bot can do ------------------------------------------


def render_and_reply(request, source, opts) -> tuple[int, dict]:
    """Render `source`, publish it as a reply to `request`. Returns the exit code
    of whichever step failed, and whatever the manifest recorded."""
    with tempfile.TemporaryDirectory(prefix="skeetio-") as tmp:
        out = Path(tmp) / "out.mp4"
        manifest = Path(tmp) / "manifest.json"
        alt = Path(tmp) / "alt.txt"
        alt.write_text(alt_text(source), encoding="utf-8")

        # 2x codes say "retry with the named change". Each attempt makes exactly
        # the change the contract names and no other — a bot that retried by
        # varying several things at once could not report which one worked. The
        # chain is bounded and every step is a documented remediation; there is
        # no general "try again" here, because a 2x that keeps failing is telling
        # us the change did not help.
        dur, generic = opts.dur, opts.generic
        code = exits.OK
        for _ in range(3):
            cmd = [sys.executable, str(RENDER / "make_video.py"),
                   "--post", source.uri, "--out", str(out),
                   "--manifest", str(manifest), "--dur", str(dur)]
            if generic:
                cmd.append("--generic")
            code = subprocess.run(cmd, check=False).returncode
            if code == exits.OK:
                break
            if code == exits.NO_AVATAR and not generic:
                generic = True          # the remediation the contract names
            elif code == exits.CLIP_TOO_SHORT and dur > 6.0:
                dur = max(6.0, dur - 4)
            else:
                break

        if code != exits.OK:
            return code, {}
        record = json.loads(manifest.read_text())

        if opts.dry_run:
            print(f"  --dry-run: rendered {out.stat().st_size/1e6:.1f} MB, not posting")
            return exits.OK, {**record, "reply_uri": None}

        pub = subprocess.run(
            [sys.executable, str(RENDER / "publish.py"),
             "--video", str(out), "--env", opts.env,
             "--alt-file", str(alt),
             "--reply-to", request.uri,
             "--rkey", ledger.rkey_for(request.uri),
             "--allow-empty-text", "--create-post",
             *(["--expect-account", opts.expect_account] if opts.expect_account else [])],
            check=False, capture_output=True, text=True,
        )
        sys.stdout.write(pub.stdout)
        sys.stderr.write(pub.stderr)
        if pub.returncode != exits.OK:
            return pub.returncode, record
        uri = next(
            (ln.split(" ", 1)[1].strip() for ln in pub.stdout.splitlines()
             if ln.startswith("uri: ")),
            f"at://{opts.bot_did}/app.bsky.feed.post/{ledger.rkey_for(request.uri)}",
        )
        return exits.OK, {**record, "reply_uri": uri}


def say(request, text: str, opts, token: str) -> None:
    """A one-line text reply, for when there is no video to give.

    They asked; answering is not initiating. It goes only to the person who
    addressed the bot, and the ledger holds it to once per request — a bot that
    could explain itself twice is a bot that can be made to argue with someone.
    """
    if opts.dry_run:
        print(f"  --dry-run: would reply {text!r}")
        return
    _req(
        f"{PDS}/xrpc/com.atproto.repo.createRecord",
        method="POST", token=token, ctype="application/json",
        body=json.dumps({
            "repo": opts.bot_did,
            "collection": "app.bsky.feed.post",
            # A separate key from the video's. They can never both happen for one
            # request today, but sharing the key would mean that if they ever
            # did, the second would collide and vanish silently.
            "rkey": ledger.rkey_for(request.uri + "#note"),
            "record": {
                "$type": "app.bsky.feed.post",
                "text": text,
                "createdAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "reply": request.thread_refs,
            },
        }).encode(),
    )


# --- one request ------------------------------------------------------------


def handle(note: dict, opts, token: str) -> None:
    uri = note["uri"]
    actor = note["author"]["did"]

    if actor == opts.bot_did:
        return  # its own posts come back as notifications; answering them loops
    if ledger.handled(uri):
        return

    try:
        request = P.fetch(uri)
    except (ApiError, urllib.error.URLError, TimeoutError, OSError, KeyError, LookupError) as e:
        print(f"{uri}: cannot read the request ({e}) — leaving it for the next pass")
        return

    # Removal first: it must work when rendering does not. But the branch is
    # entered only when the parent really is one of our own videos, not merely
    # because the word appeared. Testing the wording alone meant any ordinary
    # request containing "remove" or "delete" — "@skeetio delete this from my
    # memory" on a normal post — took this path, matched no ledger row, returned
    # without recording anything, and was re-read every three minutes forever.
    row = ledger.find_reply(request.reply_parent_uri) if request.reply_parent_uri else None
    if row and wants_removal(request.text, opts.bot_handle):
        if not ledger.may_remove(row, actor):
            # Silence toward them, but recorded: telling a stranger they are not
            # allowed invites them to work out who is, while writing nothing at
            # all would re-offer the request on every pass.
            ledger.append(ledger.Row(
                outcome="refused", request_uri=uri, requester_did=actor,
                source_uri=row.get("source_uri", ""), source_did=row.get("source_did", ""),
                at=ledger.now(), reply_uri=row["reply_uri"], note="not theirs to remove",
            ))
            print(f"  {actor} asked to remove {row['reply_uri']} and may not — ignoring")
            return

        if opts.dry_run:
            # Nothing is written either. A dry run that appends a terminal row
            # consumes the request permanently and can record a takedown that
            # never happened — after which retract.py reports nothing to remove
            # for a video that is still up.
            print(f"  --dry-run: would delete {row['reply_uri']}, writing nothing")
            return

        _req(
            f"{PDS}/xrpc/com.atproto.repo.deleteRecord",
            method="POST", token=token, ctype="application/json",
            body=json.dumps({
                "repo": opts.bot_did, "collection": "app.bsky.feed.post",
                "rkey": row["reply_uri"].rsplit("/", 1)[-1],
            }).encode(),
        )
        ledger.append(ledger.Row(
            outcome="removed", request_uri=uri, requester_did=actor,
            source_uri=row.get("source_uri", ""), source_did=row.get("source_did", ""),
            at=ledger.now(), reply_uri=row["reply_uri"], note="asked in thread",
        ))
        print(f"  removed {row['reply_uri']} at {actor}'s request")
        return

    if request.stands_alone:
        ledger.append(ledger.Row(
            outcome="refused", request_uri=uri, requester_did=actor,
            source_uri="", source_did="", at=ledger.now(), note="not a reply",
        ))
        say(request, "Reply to a post with my handle and I'll render that post.", opts, token)
        return

    try:
        source = P.fetch(request.reply_parent_uri)
    except (ApiError, urllib.error.URLError, TimeoutError, OSError, KeyError, LookupError) as e:
        print(f"{uri}: cannot read the post above it ({e}) — leaving it")
        return

    if source.did == opts.bot_did:
        return

    ledger.append(ledger.Row(
        outcome="claimed", request_uri=uri, requester_did=actor,
        source_uri=source.uri, source_did=source.did, at=ledger.now(),
    ))
    print(f"  rendering {source.uri} for @{request.handle}")
    code, record = render_and_reply(request, source, opts)

    if code == exits.OK:
        ledger.append(ledger.Row(
            outcome="posted", request_uri=uri, requester_did=actor,
            source_uri=source.uri, source_did=source.did, at=ledger.now(),
            reply_uri=record.get("reply_uri"), clip=record.get("clip"), exit_code=code,
        ))
        print(f"  posted {record.get('reply_uri')}")
        return

    # Anything left is a failure, and how it is recorded decides whether the
    # request ever comes back. Getting this wrong in the closing direction is
    # the expensive mistake: a terminal row for a transient error strands the
    # person permanently, and they are never told why.
    def _give_up(note: str) -> None:
        ledger.append(ledger.Row(
            outcome="failed", request_uri=uri, requester_did=actor,
            source_uri=source.uri, source_did=source.did, at=ledger.now(),
            exit_code=code, note=note,
        ))

    if code in (exits.BAD_ENV, exits.IDENTITY_MISMATCH):
        # The operator's configuration is wrong and it is wrong for every
        # request, not this one. Stopping is right; retrying past
        # IDENTITY_MISMATCH is retrying past the guard on posting as the wrong
        # account. No terminal row — the request was never the problem.
        print(f"  {exits.BY_CODE[code].name} — stopping the bot", file=sys.stderr)
        raise SystemExit(code)

    known = code in exits.BY_CODE
    if exits.is_retryable(code) or not known:
        # An undocumented code is something we do not understand — a crash
        # exiting 1, argparse exiting 2, a signal returning negative. Refusing
        # the request on the strength of an error we cannot classify is the
        # wrong default, so it retries; but it retries a bounded number of
        # times, because pairing is deterministic and a clip archive.org will
        # not serve fails identically forever.
        if ledger.attempts(uri) >= MAX_ATTEMPTS:
            label = exits.BY_CODE[code].name if known else f"undocumented exit {code}"
            print(f"  {label} — {MAX_ATTEMPTS} attempts, giving up", file=sys.stderr)
            _give_up(label)
            return
        print(f"  {exits.BY_CODE[code].name if known else f'exit {code}'} — will retry")
        return

    message = {
        exits.NO_TEXT: "That post has no text in it, so there's nothing to render.",
        exits.UNRENDERABLE_SCRIPT: "I don't have fonts that can draw that script yet, sorry.",
    }.get(code)
    ledger.append(ledger.Row(
        outcome="refused", request_uri=uri, requester_did=actor,
        source_uri=source.uri, source_did=source.did, at=ledger.now(),
        exit_code=code, note=exits.BY_CODE[code].name,
    ))
    if message:
        say(request, message, opts, token)


# --- the loop ---------------------------------------------------------------


def poll(opts, token: str) -> int:
    """One pass over the newest notifications.

    Deliberately no stored cursor. listNotifications is newest-first and its
    cursor paginates *backwards* into history, so a poller that saved it and
    passed it back would walk steadily into the past and then return nothing
    forever — looking, from the outside, exactly like a bot with no requests.

    Reading the same top-of-feed every pass is therefore correct, and it is safe
    because the ledger is what decides whether a request has been answered.
    Idempotency lives in one place rather than being split between a cursor and
    a record that could disagree.
    """
    # Filtered server-side. Doing it here instead would spend the limit on likes
    # and follows and silently drop mentions off the end of the page — the
    # busier the bot got, the more requests it would miss.
    res = get("app.bsky.notification.listNotifications", token,
              limit=opts.limit, reasons=[WANTED])
    notes = [n for n in res.get("notifications", []) if n.get("reason") == WANTED]
    fresh = [n for n in notes if not ledger.handled(n["uri"])]
    print(f"{len(notes)} mention(s), {len(fresh)} unanswered")

    for note in fresh:
        try:
            handle(note, opts, token)
        except ApiError as e:
            # One bad request must not end the pass. Nothing was marked terminal
            # for it, so the next pass picks it up again.
            #
            # ApiError and not HTTPError: _req converts one into the other, so a
            # handler listening for HTTPError here could never run. Every guard
            # in this file had that shape, which meant an expired app password
            # killed the bot silently every three minutes — cron only alerts on
            # a 3x exit and an uncaught RuntimeError exits 1.
            print(f"{note.get('uri')}: {e.code} {e.body[:200]}", file=sys.stderr)
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            print(f"{note.get('uri')}: {e}", file=sys.stderr)
    return len(fresh)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--env", required=True, help=".env holding the bot's credentials")
    ap.add_argument("--expect-account",
                    help="handle this bot must run as; refuses if --env holds another. "
                         "Pass it from the first run, not once something goes wrong.")
    ap.add_argument("--once", action="store_true", help="one pass and exit (for cron)")
    ap.add_argument("--interval", type=float, default=60.0,
                    help="seconds between passes when not --once (default 60)")
    ap.add_argument("--limit", type=int, default=25, help="notifications per pass")
    ap.add_argument("--dur", type=float, default=10.0, help="render length in seconds")
    ap.add_argument("--generic", action="store_true",
                    help="never use anyone's picture, whoever asked")
    ap.add_argument("--dry-run", action="store_true",
                    help="render and decide, but publish nothing and delete nothing")
    opts = ap.parse_args()

    env = read_env(Path(opts.env).expanduser())
    ident = env.get("BSKY_IDENTIFIER") or env.get("BSKY_HANDLE")
    pw = env.get("BSKY_APP_PASSWORD") or env.get("BSKY_PASSWORD")
    if not ident or not pw:
        print(f"no BSKY_IDENTIFIER / BSKY_APP_PASSWORD in {opts.env}", file=sys.stderr)
        return exits.BAD_ENV
    if opts.expect_account and opts.expect_account != ident:
        print(f"--expect-account says {opts.expect_account} but {opts.env} holds another. "
              f"Refusing to run.", file=sys.stderr)
        return exits.IDENTITY_MISMATCH
    if not opts.expect_account:
        print("warning: no --expect-account, so nothing checked which account this posts as",
              file=sys.stderr)

    try:
        sess = login(ident, pw)
    except (ApiError, urllib.error.URLError, TimeoutError, OSError, KeyError) as e:
        print(f"could not log in as {ident}: {e}", file=sys.stderr)
        return exits.FETCH_FAILED
    opts.bot_did, opts.bot_handle = sess["did"], sess.get("handle", ident)
    print(f"{opts.bot_handle} ({opts.bot_did}){' — DRY RUN' if opts.dry_run else ''}")

    while True:
        poll(opts, sess["accessJwt"])
        if opts.once:
            return exits.OK
        time.sleep(opts.interval)


if __name__ == "__main__":
    raise SystemExit(main())
